# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [22]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [23]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [24]:
chipo.loc[chipo['item_price'].idxmax(),'item_name']

'Steak Salad Bowl'

### Step 4. How many products cost more than $10.00?

In [25]:
chipo ['item_price'] = pd.to_numeric(chipo ['item_price'], astype (str).replace('$', " "),errors = 'coerce'

SyntaxError: incomplete input (1798879315.py, line 1)

In [17]:
(chipo['item_price'] > 10).sum()

TypeError: '>' not supported between instances of 'str' and 'int'

In [12]:
chipo [chipo['unit_price'] > 10.00][['item_name', 'item_price']] #верный ответ, но до него надо убрать $  и создать unit_price

KeyError: 'unit_price'

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [13]:
chipo.loc[chipo['item_price'] > 10, 'order_id'].nunique()
# no es lo mismo

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
print(chipo.loc[chipo['unit_price'] > 10, 'order_id'].nunique()) # верный ответ

NameError: name 'chipo' is not defined

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [14]:
#считаем сумму каждого заказа 
chipo.groupby('order_id')['item_price'].sum()

order_id
1       $2.39 $3.39 $3.39 $2.39
2                        $16.98
3                  $10.98 $1.69
4                  $11.75 $9.25
5                   $9.25 $4.45
                  ...
1830              $11.75 $11.25
1831          $9.25 $2.15 $1.50
1832                $8.75 $4.45
1833              $11.75 $11.75
1834         $11.25 $8.75 $8.75
Name: item_price, Length: 1834, dtype: str

In [15]:
#выводим заказы что больше $10
chipo.groupby('order_id')['item_price'].sum() > 10

TypeError: '>' not supported between instances of 'str' and 'int'

In [16]:
#считаем кол-во заказов, что больше $10
(chipo.groupby('order_id')['item_price'].sum() > 10).sum()

TypeError: '>' not supported between instances of 'str' and 'int'

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [21]:
chipo.loc[chipo['item_price'] > 10, 'order_id'].nunique()

TypeError: '>' not supported between instances of 'str' and 'int'

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [51]:
chipo['unit_price'] = chipo['item_price'] / chipo ['quantity']
chipo [['unit_price', 'item_name']]

      unit_price                              item_name
0           2.39           Chips and Fresh Tomato Salsa
1           3.39                                   Izze
2           3.39                       Nantucket Nectar
3           2.39  Chips and Tomatillo-Green Chili Salsa
4           8.49                           Chicken Bowl
...          ...                                    ...
4617       11.75                          Steak Burrito
4618       11.75                          Steak Burrito
4619       11.25                     Chicken Salad Bowl
4620        8.75                     Chicken Salad Bowl
4621        8.75                     Chicken Salad Bowl

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [26]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [ ]:
idx_implicito = chipo['item_price'].argmax()# какая строчка соотвестсвует индексу с максимальной ценой
print(idx_implicito)

607

In [29]:
idx_explicito = chipo['item_price'].idxmax()
print(idx_explicito)

607

In [57]:
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

np.int64(15)

In [59]:
chipo.nlargest (1,'item_price'), 'quantity'

(      order_id  quantity                     item_name choice_description  \
 3598      1443        15  Chips and Fresh Tomato Salsa                NaN

       item_price  unit_price
 3598       44.25        2.95  ,
 'quantity')

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [63]:
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl', 'quantity'].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [75]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]

20